[package]
name = "specblender"
version = "0.4.0"
edition = "2021"

[dependencies]
rustfft = "6.1"
indicatif = "0.17"
hound = "3.5"
ctrlc = "3.4"

[profile.release]
panic = "abort"
debug = false
strip = true
lto = true
opt-level = 3

[[bin]]
name = "specblender"
path = "src/main.rs"
